### ISSUE TITLE
Move to official organization

### ISSUE THREAD

**Issue by zenorocha** [allanim/dracula-javadoc#1]
Hey @allanim,

This is Zeno, creator of Dracula. I just this found repo, good job on that!

I'm wondering if you would like to have this become an official theme in our [Dracula organization](https://github.com/dracula)?

Let me know what you think.

**Comment by allanim** [comment]
> Hey @allanim,
> 
> This is Zeno, creator of Dracula. I just this found repo, good job on that!
> 
> I'm wondering if you would like to have this become an official theme in our [Dracula organization](https://github.com/dracula)?
> 
> Let me know what you think.

Hi Zeno,

The answer was late.

I would like to be the official theme, What should I do?

**Comment by zenorocha** [comment]
Hey @allanim, no problem at all.

I just sent you an invite to join the Dracula organization. Once you accept that, you can go ahead and transfer the repo.

Before we add it to the site, I need to ask you to follow the [template](https://github.com/dracula/template), more specifically the `README.md`, `screenshot.png` and `INSTALL.md` since those are needed for the site.

Thanks!

**Comment by allanim** [comment]
> Hey @allanim, no problem at all.
> 
> I just sent you an invite to join the Dracula organization. Once you accept that, you can go ahead and transfer the repo.
> 
> Before we add it to the site, I need to ask you to follow the [template](https://github.com/dracula/template), more specifically the `README.md`, `screenshot.png` and `INSTALL.md` since those are needed for the site.
> 
> Thanks!

Hi @zenorocha,
 
I have moved the repository and added the Dracula template format. Can you check it? And if it has problems, let me know that.

**Comment by zenorocha** [comment]
That's awesome @allanim, thanks for your work on this!

It's now live at: https://draculatheme.com/javadoc 🎉 🎉 🎉
